name: PHPUnit Tests

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: xdebug
        coverage: xdebug
        
    - name: Validate composer.json and composer.lock
      run: composer validate
      
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress
      
    - name: Run test suite
      run: composer test 